---
title: "Estudo dirigido - Mistura de distribuições"
lang: pt
format: html
author: Prof. Lupércio França Bessegato
toc: true
date: "%d/%m/%y: 27 April 2025"
---

Objetivo:  
Construir códigos na linguagem R para gerar número aleatórios de misturas de distribuições. Continuar usando, basicamente, sequência de números aleatórios uniformemente distribuídos entre 0 e 1, ou seja, usando apenas o comando runif() em R.

Leituras sugeridas:  
ROBERT, P. C.; CASELLA, G. Introducing Monte Carlo methods with R. Springer: 2010.  
ROSS, S. M. Simulation. 5th. Ed. London, UK: Academic Press, 2006.

Estudo e desenvolvimento:  
1. Leia a Seção 2.2.3 Mixture representations de ROBERT e CASELLA (2010) e acompanhe seu exemplo.  
2. Leia a Seção 4.5 The Composition Approach de ROSS (2006) e implemente o algoritmo apresentado no exemplo 4g.  
3. Leia e resolva o Exercício 7 (The Composition Method), pág. 92/315 de ROSS (2006). Implemente algoritmo para construir gerador de número de uma mistura de populações normais com médias 0 e 2 e desvio padrão 1. Considere mesmo peso para as duas populações. Verifique o que acontece quando esses pesos vão são desequlibrados em favor de uma das populações.  
4. Implemente o proposto no post "Generating data from a truncated distribution" e estude seus resultados.  
https://www.r-bloggers.com/2020/08/generating-data-from-a-truncated-distribution/  
5. Pergunta de interesse:  
Como gerar valores de um processos estocástico, com o, por exemplo de um processo de Poisson ou de uma cadeia de Markov.

# Voltar a disciplina

[Voltar](../EST066/est066.html)