---
title: "EST064 - LABORATÓRIO DE ESTATÍSTICA"
lang: pt
format: html
author: Prof. Lupércio França Bessegato
toc: true
toc_depth: 2    # Profundidade do sumário.
toc_float: 0      # Sumário flutuante na borda.
collapsed: false
smooth_scroll: false
number_sections: true   # Seções numeradas.
theme: united   # Tema usado (aparência).
highlight: tango# Cores para o destaque de código.
css: styles.css # Caminho para arquivo CSS.
fig_width: 7    # Lagura das figuras.
fig_height: 6   # Altura das figuras.
fig_caption: true       # Exibicação de legenda.
code_folding: hide      # Esconder/exibir bloco de código.
# mostrar chunk: class.source = 'fold-show'
keep_md: true   # Manter o arquivo md.
---

## Metodologia.

Plano de curso e informações sobre horários e acessos da disciplina no semestre 2025.1 está no [Moodle da Disciplina](https://ead.ufjf.br/course/view.php?id=7959){target="_blank" rel="noopener noreferrer"}.

## Introdução à linguagem R.

Fundamentos da linguagem estatística R e da interface gráfica RStudio

Slides apresentados em sala. [Slides - Introdução à Linguagem R](../EST064/01.1_introducao_fundamentos.pdf){target="_blank" rel="noopener noreferrer"}.

[Interessando-se pela linguagem R](../EST064/Interessando-se%20pela%20linguagem%20R.html){target="_blank" rel="noopener noreferrer"}.

Dicas do post:"Top Tips for Learning R from Africa R’s Shelmith Kariuki", do [R Bloggers](https://tinyurl.com/y6zw5blb){target="_blank" rel="noopener noreferrer"}.

Este é uma passo fundamental para aprender a usar a linguagem R (e qualquer outra linguagem). [Ajuda no R](../EST064/Ajuda%20no%20R.html){target="_blank" rel="noopener noreferrer"}.

Sugiro que leiam este material e refaçam seus exemplos para entender os fundamentos da linguagem em termos de estrutura de objetos e dos tipos possíveis de elementos desses objetos

[Uma revisão de fundamentos da linguagem R](../EST064/Uma%20revisão%20de%20fundamentos%20da%20linguagem%20R.html){target="_blank" rel="noopener noreferrer"}.

Alguns comandos e exercícios desse contato inicial com a linguagem R. [Uso inicial do R (1)](../EST064/Uso%20inicial%20do%20R%20(1).html){target="_blank" rel="noopener noreferrer"}.

Live apresentada durante o ERE, para a turma do semestre 2021/1, em 26/05/2021, com apresentação de: uso inicial do R: tipo de dados, ajuda no R, operações aritméticas. [Live: Uso inicial do R (ERE)](https://drive.google.com/file/d/1qm59WYfAFXgJ8UB_MCX-kZgraGN0VjLD/view?usp=sharing)

## Tipos e classes de dados em R.

Categorias baseadas em características compartilhadas pelos dados.

## Estruturas de dados em R.

### Apresentações em sala

- [Nomenclatura de objetos](../EST064/00_nomenclaturas.html){target="_blank" rel="noopener noreferrer"}.

- [Trabalhando com vetores](../EST064/01.2_introducao_vetores.pdf){target="_blank" rel="noopener noreferrer"}.

- Slides sobre data frames em R. [Trabalhando com data frames](../EST064/01.4_introducao_data-frames.pdf){target="_blank" rel="noopener noreferrer"}.

   - Repetir cuidadosamente cada exemplo em um script.

   - se errar, descubra o erro, repita e deixe no script apenas os comandos corretos.

   - Organize-se e guarde seus estudos em um script (extensão .R), documentado com seus comentários.

   - Para documentar, inicie a linha com #. O R não irá executar a partir deste caractere

   - Não se restrinja a esse material. Estude o material indicado e faça a atividade proposta!


### Material de Apoio & Estudos Dirigidos

- [Estudo dirigido - Vetores no R](../EST064/Estudo%20dirigido%20-%20Vetores%20no%20R.html){target="_blank" rel="noopener noreferrer"}.

- [Operadores básicos](../EST064/00_operadores_basicos.html){target="_blank" rel="noopener noreferrer"}.

- Leituras e estudos recomendados sobre operadores lógicos e funções relacionadas.
[Operadores básicos](../EST064/OperadoresLogicos.html){target="_blank" rel="noopener noreferrer"}.

- [Trabalhando com matrizes, fatores e listas](../EST064/01.3_introducao_matfatlis.pdf){target="_blank" rel="noopener noreferrer"}.

- [Estudo dirigido - matrizes fatores e listas no R](../EST064/Estudo%20dirigido%20-%20matrizes%20fatores%20e%20listas%20no%20R.html){target="_blank" rel="noopener noreferrer"}.

- [Estudo dirigido - Data frames](../EST064/Estudo%20dirigido%20-%20Data%20frames.html){target="_blank" rel="noopener noreferrer"}.

- [Importação e exportação de data frames](../EST064/01.5_import.pdf){target="_blank" rel="noopener noreferrer"}.

- [Estudo dirigido - Mais sobre data frames](../EST064/Estudo%20dirigido%20-%20Mais%20sobre%20data%20frames.html){target="_blank" rel="noopener noreferrer"}.


### Lives

- Live apresentada durante o ERE, para a turma do semestre 2021/1, em 01/06/2021, com apresentação de vetores no R: comandos para criação de vetores: c(), seq(), rep(); indexação de vetores. [Live: Manipulação e operação com vetores (ERE)](https://drive.google.com/file/d/1RYCGy1_KXOpDAfnQ_3M-aX1PgVOOrcl-/view?usp=sharing){target="_blank" rel="noopener noreferrer"}.

- Live apresentada durante o ERE, para a turma do semestre 2021/1, em 09/06/2021, com apresentação de cálculos vetorizados, vetores lógicos e criação de vetores aleatórios.Duração: 56:55. [Live: Vetorização (ERE)](https://drive.google.com/file/d/1M45qhDXxQ3ITUsri6-PngsNEVsiAIHVl/view?usp=sharing){target="_blank" rel="noopener noreferrer"}.

- Clipe disponibilizado durante o ERE, para a turma do semestre 2021/1, com apresentação de operadores relacionais e lógicos e de funções que atuam com valores lógicos (TRUE/FALSE). Duração: 1:06:34. [Live: Operadores Lógicos](https://drive.google.com/file/d/1W_gyvyJl5kSEAE7HdeNnfxqHrtTpA3pR/view?usp=sharing){target="_blank" rel="noopener noreferrer"}.


- Live realizada durante o ERE, para a turma do semestre 2021/1, em 16/06/2021, com apresentação dos importantes valores especiais no R (NA, NaN, Inf) e as características e as propriedades do objeto da classe matrix.Duração: 1:15:33. [Matrizes em R](https://drive.google.com/file/d/1OoehnR2fduLF7OuwvpK-7bmMYNKKcwNS/view?usp=sharing){target="_blank" rel="noopener noreferrer"}.




## Organização, colaboração e reprodução.

Diferentes estruturas disponíveis no R para organizar seus dados.

O RMarkdown permite entrelaçar códigos LaTeX e HTML com códigos R e de outras linguagens como Phyton e C++ podendo gerar textos em vários formatos: HTML, PDF e DOC. Dessa maneira, é uma ferramenta adequada para transformar suas análises estatísticas em documentos, relatórios, apresentações e até mesmo dashboards. Foi desenvolvida visando a reprodutibilidade de resultados, já que tanto código quanto narrativa estão no mesmo documento, com os resultados sendo gerados automaticamente a partir do código presente no documento.

### Funcionalidades do R Markdown

-   Compilar um documento em um relatório em diferentes formatos de saída, como PDF, HTML e Word.
-   Produzir slides para apresentações.
-   Criar dashboards interativas, com layouts que se adaptam à tela do usuário.
-   Criar relatórios interativos com Shiny.
-   Escrever artigos científicos ou livros.
-   Criar blogs ou sites.

### Fonte

Módulo 5: Apresentação de dados com relatórios, de Sillas Gonzaga\
<http://sillasgonzaga.com/material/curso_visualizacao/apresentacao-de-dados-com_relatorios.html>

### Referências

-   Cheatsheet do R Markdown
-   Guia de referência do R Markdown
-   Site do R Markdown
-   XIE, Y.; ALLAIRE, J. J.; GROLEMUND, G. R Markdown: The definitive guide. New York: Chapman and Hall, 2018.\
    <https://bookdown.org/yihui/rmarkdown/>

[The LaTeX ProjectURL](https://www.latex-project.org/){target="_blank" rel="noopener noreferrer"}.

[LaTeX](../EST064/Aula3.pdf){target="_blank" rel="noopener noreferrer"} – A document preparation system.

[Guia de edição/Fórmulas TeX (Wikipedia)](https://pt.wikipedia.org/wiki/Ajuda:Guia_de_edi%C3%A7%C3%A3o/F%C3%B3rmulas_TeX)

Sistema de tipografia [TeX](https://pt.wikipedia.org/wiki/TeX){target="_blank" rel="noopener noreferrer"}., para representar fórmulas matemáticas.

[Gerador de Tabelas em Markdown](https://www.tablesgenerator.com/markdown_tables){target="_blank" rel="noopener noreferrer"}. It's a online generator which will allow you to generate [LaTeX](../EST064/Aula3.pdf){target="_blank" rel="noopener noreferrer"} code you can just copy & paste into your document's source.

[Tabelas em HTML](https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html){target="_blank" rel="noopener noreferrer"}.

Create Awesome HTML Table with `knitr::kable` and `kableExtra`, por Hao Zhu The goal of kableExtra is to help you build common complex tables and manipulate table styles. It imports the pipe %\>% symbol from magrittr and verbalize all the functions, so basically you can add “layers” to a kable output in a way that is similar with ggplot2 and plotly

[Estudo dirigido - R Markdown](../EST064/Estudo%20dirigido%20-%20R%20Markdown.html){target="_blank" rel="noopener noreferrer"}.

Anotações de aula sobre LaTeX, do minicurso "Elaboração de Relatórios Técnicos e Páginas Web Usando R Markdown", ministrado por Calvin Silva Rodrigues. [LaTeX](../EST064/Aula3.pdf){target="_blank" rel="noopener noreferrer"}

Arquivos extensão .Rmd e sua compilação em .html, desenvolvidos na aula de 15/05/2023. [Arquivos da aula de 15/05/2023](../EST064/Arquivos%20da%20aula%20de%2015052023-20250426.zip){target="_blank" rel="noopener noreferrer"}

[R Markdown - aula do dia 21/10/2020](https://www.youtube.com/watch?v=tKUufzpoHDE){target="_blank" rel="noopener noreferrer"}.

Arquivos extensão .Rmd e sua compilação em .html [Arquivos da aula de 21/10/2020](../EST064/Arquivos%20da%20aula%20de%2021102020-20250426.zip){target="_blank" rel="noopener noreferrer"}

===============================================================================

Minicurso

Elaboração de Relatórios Técnicos e Páginas Web Usando R Markdown

Ministrante: Calvin Rodrigues

Playlist das videoaulas, slides das apresentações e material de apoio

[Minicurso: Elaboração de Relatórios Técnicos e Paginas Web Usando R Markdown](https://sites.google.com/ice.ufjf.br/encontroscomaestatistica/mincursos/minicurso-elabora%C3%A7%C3%A3o-de-relat%C3%B3rios-t%C3%A9cnicos-e-paginas-web-usando-r-markdow?authuser=0){target="_blank" rel="noopener noreferrer"}.

[Apresentações do minicurso](../EST064/Apresentação%20minicurso.pdf){target="_blank" rel="noopener noreferrer"}.

Introdução ao RStudio e ao R Markdown:

Comandos básicos [Videoaula 1 - Introdução](https://youtu.be/XkCWL0DU_8A){target="_blank" rel="noopener noreferrer"}.

Gabarito da aula 1 (arquivos Rmd e pdf) [Aula 1 - Material de apoio](../EST064/Aula%201%20-%20Material%20de%20apoio-20250426.zip){target="_blank" rel="noopener noreferrer"}.

Relatórios Técnicos: Introdução, estrutura, formatação e referências bibliográficas

[Parte I: Introdução aos relatórios técnicos](https://youtu.be/eTH4w-hhcZY){target="_blank" rel="noopener noreferrer"}.

[Parte II: Estrutura, formatação e referências bibliográficas](https://youtu.be/6hYBG9RZBUE){target="_blank" rel="noopener noreferrer"}.

Gabarito da aula 2 (arquivos Rmd, html e pdf)

[Aula 2 - Material de apoio](../EST064/Aula%202%20-%20Material%20de%20apoio-20250426.zip){target="_blank" rel="noopener noreferrer"}.

Introdução ao LaTeX LaTeX é um sistema ou programa de marcação para a editoração de documentos de alta qualidades tipográfica específico para a elaboração de textos científicos.

[Videoaula 3 - LaTeX](https://youtu.be/2-tIKlCzdxM){target="_blank" rel="noopener noreferrer"}.

[Aula 3 - Material de apoio](../EST064/Aula%203%20-%20Material%20de%20apoio-20250426.zip){target="_blank" rel="noopener noreferrer"}.

Introdução à construção de dashboards usando o R Markdown.

Introdução à construção de dashboards: Dashboard é um painel visual que contém informações, métricas e indicadores de uma situação qualquer (por exemplo, uma empresa ou projeto). Ela tem as seguintes funcionalidades: apresentar indicadores e métricas de forma objetiva e clara; embasar a tomada de decisão; acompanhar o desempenho da situação (por exemplo, empresa ou projeto); facilitar o monitoramento de dados.

[Videoaula 4 - Dashboards](https://youtu.be/B5yl880J94k){target="_blank" rel="noopener noreferrer"}.

Construção de páginas web com o R Markdown:

[Videoaula 5 - Tópicos Avançados](https://youtu.be/z4PrhZXAevM){target="_blank" rel="noopener noreferrer"}.

Dashboard postada no RPubs, criada por Calvin Rodrigues

[Exemplo de dashboard](https://rpubs.com/calvinRod/aula4){target="_blank" rel="noopener noreferrer"}.

## Visualização e descrição de dados em R.

Introdução à visualização e descrição de dados em R base.

[Slides - Visualização e descrição de dados](../EST064/02.1_visualizacao-e-descricaopdf.pdf){target="_blank" rel="noopener noreferrer"}.

[Estudo dirigido - Visualização gráfica e descrição de dados](../EST064/Estudo%20dirigido%20-%20Visualização%20gráfica%20e%20descrição%20de%20dados.html){target="_blank" rel="noopener noreferrer"}.

[Estudo dirigido - Sistema gráfico do R Base](../EST064/Estudo%20dirigido%20-%20Sistema%20gráfico%20do%20R%20Base.html){target="_blank" rel="noopener noreferrer"}.

A função plot() é uma função genérica em R, o que significa que seu comportamento pode mudar dependendo de quais tipos de dados de entrada são utilizados como argumento para a função. Em geral é usada para desenhar diagramas de dispersão, tendo com entrada os vetores com as coordenadas dos pontos. É essencial que comprendam o funcionamento da construção de gráficos no R BASE.

[Função plot()](../EST064/02_Funcao_plot.html){target="_blank" rel="noopener noreferrer"}.

## Probabilidade de eventos

Aplicações em probabilidade de eventos usando o R

Anotações de aula sobre probabilidades de eventos e distribuições de probabilidade. Leiam atentamente, refaçam e entendam seus resultados. Foquem nas funções sample() e replicate() que serão usadas intensamente em simulações.

[Probabilidade](../EST064/03_probabilidade.html){target="_blank" rel="noopener noreferrer"}.

[Estudo dirigido - Probabilidade](../EST064/Estudo%20dirigido%20-%20Probabilidade.html){target="_blank" rel="noopener noreferrer"}.

Estude atentamente estas anotações e, caso deseje, execute a atividade suplementar indicada ao final do estudo dirigido. Ela é OPCIONAL.

[Estudo dirigido - Simulação](../EST064/04_simulacao-2021.html){target="_blank" rel="noopener noreferrer"}.

## Biblioteca.

Material suplementar de apoio da disciplina do semestre 2025.1 está no [Moodle da Disciplina](https://ead.ufjf.br/course/view.php?id=7959){target="_blank" rel="noopener noreferrer"}.

===============================================================================

```{=html}
<style>
.center {
  text-align: center;
}
</style>
```

::: center
Links
:::

Livros

O presente material bibliográfico complementar está disponibilizado de maneira excepcional, para uso exclusivamente com fins didáticos, sendo vedado seu compartilhamento fora desse ambiente de aprendizagem virtual.

-   O material bibliográfico complementar será disponibilizado de maneira excepcional no Moodle da disciplina, para uso exclusivamente para fins didáticos, sendo vedado seu compartilhamento fora desse ambiente.

[Introductory Statistics with R, 2nd. ed.](https://www.cin.ufpe.br/~maod/ESAP/R/Introductory-Statistics-With-R-2nd-Edition.pdf){target="_blank" rel="noopener noreferrer"}

[R for Data Science (2e)](https://r4ds.hadley.nz/){target="_blank" rel="noopener noreferrer"}

[An Introduction to R](https://cran.r-project.org/doc/manuals/R-intro.pdf){target="_blank" rel="noopener noreferrer"}.

XIE, Y.; DERVIEUX, C.; RIEDERER, E. R Markdown cookbook. New York: CRC Press, 2020. [R Markdown cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/){target="_blank" rel="noopener noreferrer"}.

===============================================================================

::: center
Links
:::

Blogs Página

Agradeço as indicações dos discentes para compartilhar links interessantes com toda a turma.

[Instalação do R e do R Studio](../EST064/Instalação%20do%20R%20e%20do%20R%20Studio.html){target="_blank" rel="noopener noreferrer"}.

[Configuração para Compilação em PDF](../EST064/Configuração%20para%20Compilação%20em%20PDF.pdf){target="_blank" rel="noopener noreferrer"}.

[Links - Linguagem R](../EST064/Linguagem%20R.pdf){target="_blank" rel="noopener noreferrer"}.

[Links - RStudio](../EST064/RStudio.pdf){target="_blank" rel="noopener noreferrer"}.

[Links - RMarkdown](../EST064/RMarkdown.pdf){target="_blank" rel="noopener noreferrer"}.

Curso para o ensino da linguagem R, tendo o enfoco a sintaxe e semântica, pelo professor Ben David, da UFSJ - Universidade Federal de São João del-Rei. [Curso R - Programação em R (Nível Básico)](https://youtube.com/playlist?list=PL-20Z1XFWKR0y0qZdOM0KKqb4oEbAMs7O){target="_blank" rel="noopener noreferrer"}.

===============================================================================

::: center
Repositório de Arquivos
:::

[Conjuntos de Dados](../EST064/Conjuntos%20de%20Dados-20250509.zip){target="_blank" rel="noopener noreferrer"}.

Conjuntos de dados usados nas apresentações, atividades e listas de exercícios da disciplina.

[Scripts de apresentações e atividades](https://github.com/Lucas-Henriquee/Repository-in-R.git){target="_blank" rel="noopener noreferrer"}.

Página do GitHub do discente Lucas Henrique Nogueira, com os scripts de todas as aulas da disciplina. Agradeço ao Lucas pela organização e pela disponibilização do material

[Google Colab (R Notebook): Cálculo Vetorizado](https://drive.google.com/file/d/133FqMGDRsKoxj-avkbDwLoAsnRVdlZRj/view?usp=sharing){target="_blank" rel="noopener noreferrer"}.

O objetivo é os alunos comentarem e compartilharem seus códigos na solução do seguinte problema: Calcule o quadrado dos números inteiros entre 1 e 100. Some todos os pares e subtraia todo os ímpares. No final de semana, publico um clipe com seis alternativas de solução. Não há uma única solução!

Bons estudos!

## Atividades.

Atividades avaliativas da disciplina do semestre 2025.1 está no [Moodle da Disciplina](https://ead.ufjf.br/course/view.php?id=7959){target="_blank" rel="noopener noreferrer"}.
