---
title: "Estudo dirigido - Visualização gráfica e descrição de dados"
lang: pt
format: html
author: Prof. Lupércio França Bessegato
toc: true
---

Leituras sugeridas:

1. Introductory Statistics with R, by Peter Dalgaard. Leiam e refaçam exemplos da Seção 3.1: Summary statistics for a single group, na página 57; da Seção 3.2.1: Empirical cumulative distribution, na página 61; da Seção 3.2.4: Bosplots, na página 65; Seção 3.3: Summary statistics by groups, na página 65; e da Seção 3.4: Graphics for grouped data, na página 67.

2. An Introduction to R: Notes on R, a programming environment for data analysis and graphics, by W. N. Venables, D. M. Smith, and the R Core Team. Leiam atentamente, refaçam exemplos e resumam conteúdo do Chapter 12: Graphical procedures, a saber: Seção 12.1.1 The plot() function, Seção 12.1.3 Display graphics, Seção 12.1.4 Arguments to high-level plotting functions, Seção 12.2 Low-level plotting commands e Seção 12.5.1 Graphical elements, todos a partir da página 69.

3. Verifiquem atentamente o help de cada comando gráfico e sempre trabalhem com a documentação do comando par() aberta, basta teclarem help(par).

4. Importante: construir gráficos costuma ser trabalhoso em qualquer software. Não tentem queimar etapas ou procurar caminhos mais fáceis. Vocês têm de entender a estrutura com que os gráficos são construídos no R Base para conseguir, no futuro, resolver qualquer problema na construção de gráficos.

5. SÓ ACEITO GRÁFICOS CONSTRUÍDOS NO R BASE. NÃO ACEITO FUNÇÕES DE NENHUM PACOTE GRÁFICO!

Reexecutem exemplos pertinentes do material, pesquisem e conheçam mais sobre os novos comandos, pergunte ao R, ao Google, aos colegas (Fórum) e para o professor, nessa ordem (ou pode ser pra mim primeiro). Tudo que você aprender agora você utilizará quando estiver trabalhando com conjuntos de dados com milhões de colunas e milhares de colunas. Os comandos serão essencialmente os mesmos, embora você vá agregar a dificuldade do tempo para importação e de se seu computador será capaz de fazê-lo.

# Voltar a disciplina

[Voltar](../EST064/est064.html)
